apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: atlantis-github-app
  namespace: atlantis
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/ksplpxkiblaftafiljqytehbcy/items/qb7ck7jjoc7ijk3xpo6whecvhm"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: opentofu-provider-secrets
  namespace: atlantis
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/ksplpxkiblaftafiljqytehbcy/items/l5jszxlxojcknag47uv7gb2u54"
