apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cluster-oci-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
spec:
  itemPath: "vaults/ksplpxkiblaftafiljqytehbcy/items/m7oer7uouziqmucown5hau6zk4"
