apiVersion: v2
name: atlantis
description: Atlantis - Terraform/OpenTofu PR automation
type: application
version: 0.1.1
appVersion: "v0.40.0"
dependencies:
  - name: atlantis
    version: 5.27.0
    repository: https://runatlantis.github.io/helm-charts
