apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/ksplpxkiblaftafiljqytehbcy/items/enfyenzgbuio3aimuz2qfl7c3m"
