apiVersion: v2
name: burrito
description: A Helm chart for Burrito - Terraform operator for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: burrito
    version: 0.9.2
    repository: oci://ghcr.io/padok-team/charts
