burrito:
  server:
    service:
      type: NodePort

  config:
    burrito:
      datastore:
        storage:
          mock: false
          s3:
            bucket: "infra-tofu-state"
            usePathStyle: true

  tenants:
    - namespace:
        create: true
        name: "infra-tofu"
      serviceAccounts:
        - name: "infra-tofu-runner"

  datastore:
    deployment:
      envFrom:
        - secretRef:
            name: burrito-datastore-s3
