apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.metrics.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.metrics.size }}
