apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: infra-tofu-github-app
  namespace: burrito-system
  annotations:
    burrito.tf/allowed-tenants: "infra-tofu"
type: credentials.burrito.tf/shared
spec:
  itemPath: "vaults/ksplpxkiblaftafiljqytehbcy/items/qb7ck7jjoc7ijk3xpo6whecvhm"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: infra-tofu-secrets
  namespace: infra-tofu
spec:
  itemPath: "vaults/ksplpxkiblaftafiljqytehbcy/items/l5jszxlxojcknag47uv7gb2u54"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: burrito-datastore-s3
  namespace: burrito-system
spec:
  itemPath: "vaults/ksplpxkiblaftafiljqytehbcy/items/l5jszxlxojcknag47uv7gb2u54"
