apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: infra-tofu-github-app
  namespace: infra-tofu
type: credentials.burrito.tf/repository
spec:
  itemPath: "vaults/ksplpxkiblaftafiljqytehbcy/items/qb7ck7jjoc7ijk3xpo6whecvhm"
---
apiVersion: v1
kind: Secret
metadata:
  name: infra-tofu-secrets
  namespace: infra-tofu
  annotations:
    operator.1password.io/item-path: "vaults/ksplpxkiblaftafiljqytehbcy/items/l5jszxlxojcknag47uv7gb2u54"
---
apiVersion: v1
kind: Secret
metadata:
  name: burrito-datastore-s3
  namespace: burrito-system
  annotations:
    operator.1password.io/item-path: "vaults/ksplpxkiblaftafiljqytehbcy/items/l5jszxlxojcknag47uv7gb2u54"
