apiVersion: v2
name: argo-cd
description: A Helm chart for Kubernetes
type: application
version: 0.4.0
dependencies:
  - name: argo-cd
    version: 9.2.4
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-image-updater
    version: 0.12.1
    repository: https://argoproj.github.io/argo-helm
